<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AgenticGateway.Core\AgenticGateway.Core.csproj" />
    <ProjectReference Include="..\AgenticGateway.Protocols\AgenticGateway.Protocols.csproj" />
    <ProjectReference Include="..\AgenticGateway.Providers\AgenticGateway.Providers.csproj" />
    <ProjectReference Include="..\AgenticGateway.Infrastructure\AgenticGateway.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4c822706-86bc-447f-a739-dc3330876e96</UserSecretsId>
  </PropertyGroup>

</Project>
